apiVersion: v1
kind: ConfigMap
metadata:
  name: additionalScrapeConfigs
  namespace: monitoring
data:
  additionalScrapeConfigs.yaml: |
    - job_name: 'aiops-quality'
      metrics_path: /metrics
      static_configs:
        - targets:
          - aiops-quality.aiops-quality.svc.cluster.local:8000
