replicaCount: 1

image:
  repository: 8295/aiops-quality
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  MODEL_PATH: "model/model.pkl"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
