apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.21.0
    helm:
      values: |
        server:
          persistentVolume:
            enabled: false

          extraScrapeConfigs: |
            - job_name: 'pushgateway'
              static_configs:
                - targets:
                  - pushgateway.monitoring.svc.cluster.local:9091

            - job_name: 'aiops-quality'
              metrics_path: /metrics
              static_configs:
                - targets:
                  - aiops-quality.aiops-quality:8000

        pushgateway:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
